# Generated by Django 4.2.3 on 2023-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_list',
            fields=[
                ('Id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('doc_type', models.IntegerField(choices=[(1, 'General Practitioner'), (2, 'Physician'), (3, 'Cardiologist'), (4, 'Gastroenterologist'), (5, 'Dermatologist'), (6, 'Neurologist'), (7, 'Orthopedic Surgeon'), (8, 'Pediatrician'), (9, 'Gynecologist'), (10, 'Urologist'), (11, 'Nephrologist'), (12, 'Psychiatrist'), (13, 'Dentist'), (14, 'Physiotherapist'), (15, 'Ophthalmologist'), (16, 'Allergist/Immunologist'), (17, 'Pulmonologist'), (18, 'Endocrinologist'), (19, 'ENT Specialist (Ear, Nose, and Throat)')])),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')])),
                ('experience', models.IntegerField()),
                ('fees', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('Id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')])),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='patient_sessions',
            fields=[
                ('doc_Id', models.CharField(max_length=3)),
                ('session_Id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('pat_Id', models.CharField(max_length=5)),
                ('session_date', models.DateField()),
                ('session_time', models.IntegerField(choices=[(10, '10:00 AM'), (14, '02:00 PM'), (17, '05:00 PM')])),
            ],
        ),
        migrations.CreateModel(
            name='doctor_sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_Id', models.CharField(max_length=3)),
                ('session_date', models.DateField()),
                ('session_time', models.IntegerField(choices=[(10, '10:00 AM'), (14, '02:00 PM'), (17, '05:00 PM')])),
                ('session_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('session_time', 'session_date', 'doc_Id')},
            },
        ),
    ]
