# Generated by Django 4.2.3 on 2024-01-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor_sessions',
            new_name='doctor_session',
        ),
        migrations.RenameModel(
            old_name='patient_sessions',
            new_name='patient_session',
        ),
    ]
